name: rna-data-products
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.11
  - pip
  - numpy>=1.16.5
  - scipy>=1.4.0
  - h5py>=3
  - natsort
  - pip:
      - anndata==0.9.2
      - awswrangler
      - leidenalg
      - manhole
      - pandas
      - pyyaml
      - requests
      - scanpy
      - awscli==1.18.105
      - botocore==1.17.28
      - zarr